name: Java_Spring_pipeline

on:
  push:
    branches:
      - master

jobs:
  checkstyle_project:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone repo
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Change permission for mvnw
        run: chmod +x mvnw

      - name: Check style project
#        continue-on-error: true
        run: |
          pip install pycodestyle
          pycodestyle .
